apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.app.name }}
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.app.name }}
          image: franticmax/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: postgres_host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.app.postgres.name }}-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.app.postgres.name }}-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.app.postgres.name }}-secret
                  key: POSTGRES_USER
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.app.postgres.name }}-secret
                  key: POSTGRES_PORT