apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Release.Name }}-{{ .Values.app.name }}-ingress
    labels:
      app: ingress-nginx
spec:
    ingressClassName: nginx
    rules:
      - host: {{ .Values.app.host }}
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ .Release.Name }}-{{ .Values.app.name }}-service
                  port:
                    number: {{ .Values.app.port }}
