apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-chart-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi