apiVersion: v1
kind: PersistentVolume
metadata:
    name: user-service-chart-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"