apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Release.Name }}-{{ .Values.postgres.name }}-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"